### ISSUE TITLE
review

### ISSUE THREAD

**Issue by vobencha** [RTCGA/RTCGA.mRNA.20160128#1]
Thanks for incorporating the changes mentioned in https://github.com/RTCGA/RTCGA.CNV.20160128/issues/1#issuecomment-269777502.

1) vignette
The packages need workflow-style vignettes. You need to show a mini example of an analysis someone might do with these data. Why are they useful? Can the files in the package be used together?

2) man page
- Mention what type of data these are, expression, counts, etc.
- What are the rows? Do these represent genes or other features?
- What are the columns? Samples? If yes, are these the same for all datasets? Were they case-control, disease-healthy or ?

3) roxygen issue
I'm not very familiar with roxygen so not of much help here. I supposed you've tried something like this -

#' @export
#’ @param metadata Logical indicating if metadata or resource should be loaded
BRCA.mRNA.20160128 <- function(metadata = FALSE) {}

**Comment by LiNk-NY** [comment]
Hi @MarcinKosinski, 
CC @vobencha, 
You mentioned you were having some issues with the usage output in your documentation. 

Assuming you are documenting a function: 
The usage section gets generated automatically from your function and it is based on your defaults. Ideally, you don't want to override this behaviour. But if you do, you can use the `@usage` tag followed by a string. 

Regards,
Marcel

**Comment by vobencha** [comment]
Looks like this is a dead issue. Closing it.
